#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Darbu_sarasas
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Darbau_DB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDarbai(Darbai instance);
    partial void UpdateDarbai(Darbai instance);
    partial void DeleteDarbai(Darbai instance);
    partial void InsertDarbuotojai(Darbuotojai instance);
    partial void UpdateDarbuotojai(Darbuotojai instance);
    partial void DeleteDarbuotojai(Darbuotojai instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Darbu_sarasas.Properties.Settings.Default.Darbau_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Darbai> Darbais
		{
			get
			{
				return this.GetTable<Darbai>();
			}
		}
		
		public System.Data.Linq.Table<Darbuotojai> Darbuotojais
		{
			get
			{
				return this.GetTable<Darbuotojai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Darbai")]
	public partial class Darbai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Darbuotojo_Id;
		
		private string _Darbas;
		
		private System.DateTime _Darbo_pr;
		
		private System.Nullable<System.DateTime> _Darbo_pab;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnDarbuotojo_IdChanging(int value);
    partial void OnDarbuotojo_IdChanged();
    partial void OnDarbasChanging(string value);
    partial void OnDarbasChanged();
    partial void OnDarbo_prChanging(System.DateTime value);
    partial void OnDarbo_prChanged();
    partial void OnDarbo_pabChanging(System.Nullable<System.DateTime> value);
    partial void OnDarbo_pabChanged();
    #endregion
		
		public Darbai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darbuotojo_Id", DbType="Int NOT NULL")]
		public int Darbuotojo_Id
		{
			get
			{
				return this._Darbuotojo_Id;
			}
			set
			{
				if ((this._Darbuotojo_Id != value))
				{
					this.OnDarbuotojo_IdChanging(value);
					this.SendPropertyChanging();
					this._Darbuotojo_Id = value;
					this.SendPropertyChanged("Darbuotojo_Id");
					this.OnDarbuotojo_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darbas", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Darbas
		{
			get
			{
				return this._Darbas;
			}
			set
			{
				if ((this._Darbas != value))
				{
					this.OnDarbasChanging(value);
					this.SendPropertyChanging();
					this._Darbas = value;
					this.SendPropertyChanged("Darbas");
					this.OnDarbasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darbo_pr", DbType="Date NOT NULL")]
		public System.DateTime Darbo_pr
		{
			get
			{
				return this._Darbo_pr;
			}
			set
			{
				if ((this._Darbo_pr != value))
				{
					this.OnDarbo_prChanging(value);
					this.SendPropertyChanging();
					this._Darbo_pr = value;
					this.SendPropertyChanged("Darbo_pr");
					this.OnDarbo_prChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darbo_pab", DbType="Date")]
		public System.Nullable<System.DateTime> Darbo_pab
		{
			get
			{
				return this._Darbo_pab;
			}
			set
			{
				if ((this._Darbo_pab != value))
				{
					this.OnDarbo_pabChanging(value);
					this.SendPropertyChanging();
					this._Darbo_pab = value;
					this.SendPropertyChanged("Darbo_pab");
					this.OnDarbo_pabChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Darbuotojai")]
	public partial class Darbuotojai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Vardas;
		
		private string _Pavarde;
		
		private string _Pareigos;
		
		private string _El_pastas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVardasChanging(string value);
    partial void OnVardasChanged();
    partial void OnPavardeChanging(string value);
    partial void OnPavardeChanged();
    partial void OnPareigosChanging(string value);
    partial void OnPareigosChanged();
    partial void OnEl_pastasChanging(string value);
    partial void OnEl_pastasChanged();
    #endregion
		
		public Darbuotojai()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vardas", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Vardas
		{
			get
			{
				return this._Vardas;
			}
			set
			{
				if ((this._Vardas != value))
				{
					this.OnVardasChanging(value);
					this.SendPropertyChanging();
					this._Vardas = value;
					this.SendPropertyChanged("Vardas");
					this.OnVardasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavarde", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Pavarde
		{
			get
			{
				return this._Pavarde;
			}
			set
			{
				if ((this._Pavarde != value))
				{
					this.OnPavardeChanging(value);
					this.SendPropertyChanging();
					this._Pavarde = value;
					this.SendPropertyChanged("Pavarde");
					this.OnPavardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pareigos", DbType="NVarChar(MAX)")]
		public string Pareigos
		{
			get
			{
				return this._Pareigos;
			}
			set
			{
				if ((this._Pareigos != value))
				{
					this.OnPareigosChanging(value);
					this.SendPropertyChanging();
					this._Pareigos = value;
					this.SendPropertyChanged("Pareigos");
					this.OnPareigosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[El.pastas]", Storage="_El_pastas", DbType="NVarChar(MAX)")]
		public string El_pastas
		{
			get
			{
				return this._El_pastas;
			}
			set
			{
				if ((this._El_pastas != value))
				{
					this.OnEl_pastasChanging(value);
					this.SendPropertyChanging();
					this._El_pastas = value;
					this.SendPropertyChanged("El_pastas");
					this.OnEl_pastasChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
